# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='category_icon_addon_category', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CategoryIcon',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='category_icon_addon_categoryicon', serialize=False, to='cms.CMSPlugin')),
                ('url_link', models.URLField()),
                ('link_title', models.CharField(blank=True, max_length=200)),
                ('extra_classes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='categoryicon',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_icon_addon.Icon'),
        ),
        migrations.AddField(
            model_name='categoryicon',
            name='icon_image',
            field=filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
