# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_icon_addon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryicon',
            name='url_link',
        ),
        migrations.AddField(
            model_name='categoryicon',
            name='url',
            field=models.CharField(blank=True, help_text='If present, clicking on image will take user to link.', max_length=255, null=True, verbose_name='link'),
        ),
    ]
